version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /root/willowdatabase/dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: unless-stopped

  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"  # Changed to 8000:8000 to avoid conflict with Nginx listening on port 80
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      SUPERUSER_CREATE: "true"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_PASSWORD: "admin"
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
    volumes:
      - static_volume:/app/static  # Define where Django collects static files

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - web
    volumes:
      - static_volume:/app/static
      - /etc/letsencrypt/live/willowbrookeducation.net/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/willowbrookeducation.net/privkey.pem:/etc/nginx/certs/privkey.pem

volumes:
  db_data:
    driver: local
    driver_opts:
      type: 'none'
      device: ${DB_VOLUME_PATH}
      o: 'bind'
  static_volume: {}
